FROM alpine:edge
RUN apk add --no-cache openjdk17 
RUN mkdir -p /opt/wezva
WORKDIR /opt/wezva
COPY target/wezva-springboot-docker-0.1.0.jar app.jar
COPY app.properties app.properties
COPY bootstrap.sh bootstrap.sh
RUN chmod +x bootstrap.sh
EXPOSE 8080
ENTRYPOINT ["/bin/sh", "bootstrap.sh"]
